version: "3"
services:
  web:
    build: .
    env_file:
      .env.dev
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - public:/app/public
      - tmp:/app/tmp
    depends_on:
      - db

  db:
    image: mysql:8.0
    # trilogy
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql

  nginx:
      build:
        context: docker/nginx
      ports:
        - "80:80"
      volumes:
        - public:/app/public
        - tmp:/app/tmp
      depends_on:
        - web

volumes:
  bundle:
  node_modules:
  mysql:
  public:
  tmp:
