name: "CI and Deploy to ECS"
  push:
    branches:
      - master
jobs:
  ci_workflow:
    uses: ./.github/workflows/ci.yml
  deploy:
    runs-on: ubuntu-latest
    needs: ci_workflow
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout ecspresso
        uses: kayac/ecspresso@v2
        with:
          version: latest

      - name: ecspresso diff
        run: |
          ecspresso diff

      - name: ecspresso verify
        run: |
          ecspresso verify

      - name: ecspresso deploy
        run: |
          ecspresso deploy
